[package]
name = "copy_sign_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitness = "0.4.0"
log = "0.4.19"
thiserror = "1.0.44"
winreg = "0.50.0"
fs_extra="1.3.0"
